### ISSUE TITLE
Possibility to improve the performance

### ISSUE THREAD

**Issue by jiaohaibin** [NSHipster/DBSCAN#1]
Dear Mattt,

When I am testing this lib with 1000 points which are very close to each other, most of the distance are smaller than the epsilon. I found neighbor will be added to neighbors again and again, though it has been marked with a label.

Best Regards,
Haibin

**Comment by mattt** [comment]
See https://github.com/NSHipster/DBSCAN/pull/2#issuecomment-791449410
